volumes:
  postgres_data:

networks:
  main_network:
  django_network:


services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - main_network
    depends_on:
      - django
    container_name: nginx_dev

  django:
    build:
      context: .
    restart: always
    expose:
      - 8000
    env_file:
      - ./docker/.env
    volumes:
      - ./:/app
    networks:
      - main_network
      - django_network
    depends_on:
      - postgres
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --workers=2 --max-requests=500 backend.wsgi -b 0.0.0.0:8000"
    container_name: django_dev

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./docker/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - django_network
    container_name: postgres_dev
