volumes:
  postgres_data:

networks:
  nginx_network:
  main_network:


services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx_network
    depends_on:
      - django
    container_name: nginx_todo

  django:
    build:
      context: .
    restart: always
    expose:
      - 8000
    env_file:
      - ./docker/.env
    networks:
      - nginx_network
      - main_network
    depends_on:
      - postgres
    command: bash -c "
      python manage.py makemigrations --merge &&
      python manage.py migrate &&
      gunicorn --workers=2 --max-requests=500 backend.wsgi -b 0.0.0.0:8000"
    container_name: django_todo

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - ./docker/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - main_network
    container_name: postgres_todo
