version: "3.9"

volumes:
  pgdata:


services:
  django:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - docker/env/.env.prod
    volumes:
      - ./:/app
    depends_on:
      - postgres
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --workers=4 --reload --max-requests=1000 backend.wsgi -b 0.0.0.0:8000"
    container_name: todo_django_prod

  nginx:
    image: nginx:stable-alpine
    restart: always
    working_dir: /app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/dev/:/etc/nginx/conf.d:ro
      - ./docker/nginx/prod/:/etc/nginx/conf.d:ro
      - ./docker/certbot/conf:/etc/letsencrypt:ro
      - ./docker/certbot/www:/var/www/certbot:ro
    links:
      - django
    depends_on:
      - django
    container_name: todo_nginx_prod

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - docker/env/.env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data/
    container_name: todo_postgres_prod

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt:rw
      - ./docker/certbot/www:/var/www/certbot:rw
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email <your_email> --agree-tos --no-eff-email -d <domain (example.com)> -d <domain (www.example.com)>
    depends_on:
      - nginx
    container_name: todo_certbot_prod
